---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
- name: standalone
  run_list:
  - recipe[minitest-handler]
  - recipe[carbon_test::standalone]
  attributes: 
- name: twoplusrelay
  run_list:
  - recipe[minitest-handler]
  - recipe[carbon_test::twoplusrelay]
  attributes: 
- name: relayplus
  run_list:
  - recipe[minitest-handler]
  - recipe[carbon_test::relayplus]
  attributes: 
