---
driver:
  name: vagrant

driver_config:
    customize:
          memory: 1024
          cpus: 4
          

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
- name: standalone
  run_list:
  - recipe[minitest-handler]
  - recipe[carbon_test::standalone]
  attributes: 
- name: twoplusrelay
  run_list:
  - recipe[minitest-handler]
  - recipe[carbon_test::twoplusrelay]
  attributes: 
- name: relayplus
  run_list:
  - recipe[minitest-handler]
  - recipe[carbon_test::relayplus]
  attributes: 
